WITH CHARLIES_ALLSTATES AS
(
    SELECT 
    SUM("PRODUCT_PRICE") AS "sum_PRODUCT_PRICE", 
    COUNT("TRANSACTION_ID") AS "count_TRANSACTION_ID", 
    "STATE", 
    "TRANSACTION_YEAR" 
    FROM ({{ ref('STG_CHARLIES_SALES_ALLSTATES') }}) 
    GROUP BY ("STATE", 
            "TRANSACTION_YEAR")
)

SELECT 
  *, 
  RANK() OVER (ORDER BY "sum_PRODUCT_PRICE" DESC) AS "Rank" 
FROM CHARLIES_ALLSTATES