WITH CHARLIES_ALLSTATES AS
(
    SELECT 
    SUM("PRODUCT_PRICE") AS "sum_PRODUCT_PRICE", 
    COUNT("TRANSACTION_ID") AS "count_TRANSACTION_ID", 
    "PRODUCT_NAME", 
    "TRANSACTION_MONTH" 
    FROM ({{ ref('STG_CHARLIES_SALES_ALLSTATES') }}) 
    WHERE "TRANSACTION_YEAR" = '2024'
    GROUP BY ("PRODUCT_NAME", 
            "TRANSACTION_MONTH")
)

SELECT 
  *, 
  RANK() OVER (ORDER BY "sum_PRODUCT_PRICE" DESC) AS "Rank" 
FROM CHARLIES_ALLSTATES