version: 2

models:
  - name: STG_CHARLIES_SALES_ALLSTATES
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          max_value: 75000 # (Optional)
      - dbt_expectations.expect_table_column_count_to_equal:
          value: 21          
    columns:
      - name: TRANSACTION_ID
        description: "Unique ID for each sale"
        tests:
          - unique:
            config:
              where: "TRANSACTION_DATE <= LAST_UPDATED"
      - name: TRANSACTON_YEAR
        tests:
          - dbt_expectations.expect_column_values_to_match_regex:
            regex: "^\d+$"
      - name: TRANSACTON_MONTH
        tests:
          - dbt_expectations.expect_column_values_to_match_regex:
            regex: "^\d+$"
      - name: PRODUCT_PRICE
        tests:
          - dbt_expectations.expect_column_values_to_match_regex:
            regex: "^\d+$"
#      - name: watch_priority
#        description: "Analysis of watch priority"
#        tests:
#          - dbt_expectations.expect_column_to_exist
#          - not_null     
#      - name: synopsis
#        #meta:
#          #masking_policy: mp_encrypt_pii
#        tests:
#          - dbt_expectations.expect_column_values_to_be_of_type:
#              column_type: VARCHAR
#      - name: id
#        description: "Netflix ID"
#        tests:
#          - unique
#      - name: title
#        description: "Title of movie"
#        tests:
#          - not_null
#      - name: year
#        description: "Release year"
#        tests:
#          - not_null
