{% macro stg_charlies_sales (grain) %}
SELECT
    LAST_UPDATED,
    STORE_LOCATION,
    {{ grain }} as STATE,
    TRANSACTION_ID,
    DATE_PART(year,"TRANSACTION_DATE") as TRANSACTION_YEAR,
    DATE_PART(month,"TRANSACTION_DATE") as TRANSACTION_MONTH,
    PRODUCT_NAME,
    SALE_INDICATOR,
    PRODUCT_PRICE,
    REVIEW_INDICATOR,
    REVIEW 
from {{source('CHARLIES_SHOE_EMPORIUM',"SRC_CHARLIES_SHOE_EMPORIUM_SALES_{{ grain }}")}}
{% endmacro %}