version: 2

sources:
  - name: CHARLIES_SHOE_EMPORIUM
    database: "{{ env_var('DBT_TARGET_DATABASE') }}"
    schema: "{{ env_var('DBT_TARGET_SCHEMA') }}"
    loaded_at_field: LAST_UPDATED
    tables:
      - name: STG_CHARLIES_SALES
      - name: SRC_CHARLIES_SHOE_EMPORIUM_SALES
      - name: SRC_CHARLIES_SHOE_EMPORIUM_SALES_OR
      - name: SRC_CHARLIES_SHOE_EMPORIUM_SALES_CO
