SELECT
  LAST_UPDATED,
  STORE_LOCATION,
  'FL' as STATE,
  TRANSACTION_ID,
  TRANSACTION_DATE,
  PRODUCT_NAME,
  SALE_INDICATOR,
  PRODUCT_PRICE,
  REVIEW_INDICATOR,
  REVIEW
FROM {{source('CHARLIES_SHOE_EMPORIUM','SRC_CHARLIES_SHOE_EMPORIUM_SALES')}}