{% macro dim_charlies_sales(grain) %}

SELECT
    SALES.STORE_ID,
    SALES.LOCATION_NAME,
    SALES.STATE,
    GM.GM_NAME,
    SALES.TRANSACTION_ID,
    SALES.TRANSACTION_YEAR,
    SALES.TRANSACTION_MONTH,
    SALES.PRODUCT_NAME, 
    SALES.SALE_INDICATOR, 
    SALES.PRODUCT_PRICE, 
    SALES.REVIEW, 
    SALES.PRIMARY_COLOR, 
    SALES.SECONDARY_COLAR, 
    SALES.PRODUCT_LINE, 
    SALES.COMFORT, 
    SALES.RESPONSIVENESS, 
    SALES.WEIGHT_OZ, 
    SALES.CUSHIONING, 
    SALES.BREATHABILITY
FROM {{ source('CHARLIES','STG_CHARLIES_SALES_ALLSTATES') }} as SALES
LEFT JOIN {{ source('CHARLIES','STORE_GM_NAMES')}} as GM
    ON SALES.STORE_ID = GM.STORE_ID
WHERE
    SALES.STATE = '{{ grain }}'

{% endmacro %}