version: 2

sources:
  - name: CHARLIES_SHOE_EMPORIUM
    database: "{{ env_var('DBT_TARGET_DATABASE') }}"
    schema: "{{ env_var('DBT_TARGET_SCHEMA') }}"
    tables:
      - name: STG_CHARLIES_SALES
        columns:
          - name: TRANSACTION_ID
            tests:
              - unique:
                  config:
                    store_failures: true
              - not_null:
                  config:
                    store_failures: true                
          - name: SALE_INDICATOR
            tests: 
              - dbt_expectations.expect_column_to_exist:
                  config:
                    store_failures: true                    
              - accepted_values:
                  values: ['true','false']
                  #values: ['false']
                  config:
                    store_failures: true               
          - name: PRODUCT_NAME
            tests:
              - dbt_expectations.expect_column_distinct_count_to_be_less_than:
                  value: 16
        loaded_at_field: LAST_UPDATED
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 5
            period: day